# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/user/user_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/user/user_response.proto", :syntax => :proto3) do
    add_message "rpc.user.UserResponse" do
      optional :id, :int64, 1
      optional :name, :string, 2
    end
  end
end

module Rpc
  module User
    UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.user.UserResponse").msgclass
  end
end
