# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/order_item.proto

require 'google/protobuf'

require 'rpc/product/product_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/order_item.proto", :syntax => :proto3) do
    add_message "rpc.order.OrderItem" do
      optional :id, :string, 1
      optional :price, :int32, 2
      optional :quantity, :int32, 3
      optional :amount, :int32, 4
      optional :product, :message, 5, "rpc.product.ProductResponse"
    end
  end
end

module Rpc
  module Order
    OrderItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.OrderItem").msgclass
  end
end
