# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'order_service_pb.rb'

module Rpc
  module Order
    class OrderService < Twirp::Service
      package 'rpc.order'
      service 'Order'
      rpc :Create, Google::Protobuf::Empty, Rpc::Order::OrderResource, :ruby_method => :create
      rpc :Show, Rpc::Order::ShowRequest, Rpc::Order::OrderResource, :ruby_method => :show
    end

    class OrderClient < Twirp::Client
      client_for OrderService
    end
  end
end
