# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/order_service.proto

require 'google/protobuf'

require 'rpc/order/show_request_pb'
require 'rpc/order/order_resource_pb'
require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/order_service.proto", :syntax => :proto3) do
  end
end

module Rpc
  module Order
  end
end
