# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/update_product_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/update_product_request.proto", :syntax => :proto3) do
    add_message "rpc.order.UpdateProductRequest" do
      optional :order_id, :string, 1
      optional :product_id, :string, 2
      optional :quantity, :int32, 3
    end
  end
end

module Rpc
  module Order
    UpdateProductRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.UpdateProductRequest").msgclass
  end
end
