// @generated by protobuf-ts 2.0.0-alpha.20 with parameters long_type_number,generate_dependencies
// @generated from protobuf file "product_service.proto" (syntax proto3)
// tslint:disable
import { ProductsResponse } from './products_response'
import { Empty } from './google/protobuf/empty'
import { ProductResponse } from './product_response'
import { ProductShowRequest } from './product_show_request'
import { ServiceType } from '@protobuf-ts/runtime-rpc'
/**
 * @generated ServiceType for protobuf service Product
 */
export const Product = new ServiceType('Product', [
  { name: 'Show', options: {}, I: ProductShowRequest, O: ProductResponse },
  { name: 'Index', options: {}, I: Empty, O: ProductsResponse },
])
