// @generated by protobuf-ts 2.0.0-alpha.20 with parameters long_type_number,generate_dependencies
// @generated from protobuf file "user_index_request.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime'
import type { IBinaryWriter } from '@protobuf-ts/runtime'
import { UnknownFieldHandler } from '@protobuf-ts/runtime'
import type { BinaryReadOptions } from '@protobuf-ts/runtime'
import type { IBinaryReader } from '@protobuf-ts/runtime'
import { MessageType } from '@protobuf-ts/runtime'
/**
 * @generated from protobuf message UserIndexRequest
 */
export interface UserIndexRequest {}
// @generated message type with reflection information, may provide speed optimized methods
class UserIndexRequest$Type extends MessageType<UserIndexRequest> {
  constructor() {
    super('UserIndexRequest', [])
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UserIndexRequest
  ): UserIndexRequest {
    return target ?? this.create()
  }
  internalBinaryWrite(
    message: UserIndexRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    let u = options.writeUnknownFields
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer
      )
    return writer
  }
}
/**
 * @generated MessageType for protobuf message UserIndexRequest
 */
export const UserIndexRequest = new UserIndexRequest$Type()
