# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/product/product_service.proto

require 'google/protobuf'

require 'rpc/product/show_request_pb'
require 'rpc/product/product_response_pb'
require 'rpc/product/products_response_pb'
require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/product/product_service.proto", :syntax => :proto3) do
  end
end

module Rpc
  module Product
  end
end
