# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_show_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product_show_request.proto", :syntax => :proto3) do
    add_message "ProductShowRequest" do
      optional :id, :string, 1
    end
  end
end

ProductShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductShowRequest").msgclass
