# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_index_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product_index_request.proto", :syntax => :proto3) do
    add_message "ProductIndexRequest" do
    end
  end
end

ProductIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductIndexRequest").msgclass
