# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_response.proto

require 'google/protobuf'

require 'product_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("products_response.proto", :syntax => :proto3) do
    add_message "ProductsResponse" do
      repeated :products, :message, 1, "ProductResponse"
    end
  end
end

ProductsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductsResponse").msgclass
