# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product_response.proto", :syntax => :proto3) do
    add_message "ProductResponse" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :price, :int32, 3
    end
  end
end

ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductResponse").msgclass
