# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_service.proto

require 'google/protobuf'

require 'product_show_request_pb'
require 'product_response_pb'
require 'product_index_request_pb'
require 'products_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product_service.proto", :syntax => :proto3) do
  end
end

