# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'product_service_pb.rb'

class ProductService < Twirp::Service
  service 'Product'
  rpc :Show, ProductShowRequest, ProductResponse, :ruby_method => :show
  rpc :Index, ProductIndexRequest, ProductsResponse, :ruby_method => :index
end

class ProductClient < Twirp::Client
  client_for ProductService
end
