# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'test_service_pb.rb'

module Test
  class TestService < Twirp::Service
    package 'test'
    service 'Test'
  end

  class TestClient < Twirp::Client
    client_for TestService
  end
end
