# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("test_service.proto", :syntax => :proto3) do
  end
end

module Test
end
