# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_create_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_create_request.proto", :syntax => :proto3) do
    add_message "UserCreateRequest" do
      optional :name, :string, 1
    end
  end
end

UserCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserCreateRequest").msgclass
