# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_index_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_index_request.proto", :syntax => :proto3) do
    add_message "UserIndexRequest" do
    end
  end
end

UserIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserIndexRequest").msgclass
