# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_show_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_show_request.proto", :syntax => :proto3) do
    add_message "UserShowRequest" do
      optional :id, :int64, 1
    end
  end
end

UserShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserShowRequest").msgclass
