# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_response.proto", :syntax => :proto3) do
    add_message "UserResponse" do
      optional :id, :int64, 1
      optional :name, :string, 2
    end
  end
end

UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserResponse").msgclass
