# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/product/products_response.proto

require 'google/protobuf'

require 'rpc/product/product_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/product/products_response.proto", :syntax => :proto3) do
    add_message "rpc.product.ProductsResponse" do
      repeated :products, :message, 1, "rpc.product.ProductResponse"
    end
  end
end

module Rpc
  module Product
    ProductsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.product.ProductsResponse").msgclass
  end
end
