# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/product/show_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/product/show_request.proto", :syntax => :proto3) do
    add_message "rpc.product.ShowRequest" do
      optional :id, :string, 1
    end
  end
end

module Rpc
  module Product
    ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.product.ShowRequest").msgclass
  end
end
