# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/user/create_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/user/create_request.proto", :syntax => :proto3) do
    add_message "rpc.user.CreateRequest" do
      optional :name, :string, 1
    end
  end
end

module Rpc
  module User
    CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.user.CreateRequest").msgclass
  end
end
