# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/user/show_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/user/show_request.proto", :syntax => :proto3) do
    add_message "rpc.user.ShowRequest" do
      optional :id, :int64, 1
    end
  end
end

module Rpc
  module User
    ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.user.ShowRequest").msgclass
  end
end
