# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'user_service_pb.rb'

module Rpc
  module User
    class UserService < Twirp::Service
      package 'rpc.user'
      service 'User'
      rpc :Show, Rpc::User::ShowRequest, Rpc::User::UserResponse, :ruby_method => :show
      rpc :Create, Rpc::User::CreateRequest, Rpc::User::UserResponse, :ruby_method => :create
      rpc :Index, Google::Protobuf::Empty, Rpc::User::UsersResponse, :ruby_method => :index
    end

    class UserClient < Twirp::Client
      client_for UserService
    end
  end
end
