# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/user/user_service.proto

require 'google/protobuf'

require 'rpc/user/show_request_pb'
require 'rpc/user/create_request_pb'
require 'rpc/user/user_response_pb'
require 'rpc/user/users_response_pb'
require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/user/user_service.proto", :syntax => :proto3) do
  end
end

module Rpc
  module User
  end
end
