# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

class UserService < Twirp::Service
  service 'User'
  rpc :Show, UserShowRequest, UserResponse, :ruby_method => :show
  rpc :Create, UserCreateRequest, UserResponse, :ruby_method => :create
end

class UserClient < Twirp::Client
  client_for UserService
end
