# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/service.proto

require 'google/protobuf'

require 'user/user_show_request_pb'
require 'user/user_create_request_pb'
require 'user/user_response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user/service.proto", :syntax => :proto3) do
  end
end

