# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/cart_service.proto

require 'google/protobuf'

require 'rpc/order/update_product_request_pb'
require 'rpc/order/order_resource_pb'
require 'rpc/order/update_shipping_address_request_pb'
require 'rpc/order/complete_request_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/cart_service.proto", :syntax => :proto3) do
  end
end

module Rpc
  module Order
  end
end
