# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/complete_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/complete_request.proto", :syntax => :proto3) do
    add_message "rpc.order.CompleteRequest" do
      optional :order_id, :string, 1
    end
  end
end

module Rpc
  module Order
    CompleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.CompleteRequest").msgclass
  end
end
