# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/shipping_address_resource.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/shipping_address_resource.proto", :syntax => :proto3) do
    add_message "rpc.order.ShippingAddressResource" do
      optional :id, :string, 1
      optional :address1, :string, 2
      optional :address2, :string, 3
      optional :city, :string, 4
      optional :country, :string, 5
      optional :name, :string, 6
      optional :phone, :string, 7
      optional :zip, :string, 8
    end
  end
end

module Rpc
  module Order
    ShippingAddressResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.ShippingAddressResource").msgclass
  end
end
