# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/show_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/show_request.proto", :syntax => :proto3) do
    add_message "rpc.order.ShowRequest" do
      optional :id, :string, 1
    end
  end
end

module Rpc
  module Order
    ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.ShowRequest").msgclass
  end
end
