# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/order/update_shipping_address_request.proto

require 'google/protobuf'

require 'rpc/order/shipping_address_resource_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/order/update_shipping_address_request.proto", :syntax => :proto3) do
    add_message "rpc.order.UpdateShippingAddressRequest" do
      optional :order_id, :string, 1
      optional :shipping_address, :message, 2, "rpc.order.ShippingAddressResource"
    end
  end
end

module Rpc
  module Order
    UpdateShippingAddressRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.order.UpdateShippingAddressRequest").msgclass
  end
end
